### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by darshilparmar** [clchiou/startup#1]
pip install startup
Collecting startup
  Using cached https://files.pythonhosted.org/packages/64/b8/796138d30370d2bc957b94a6003efb19a63440d0f39d236815d033dd017d/startup-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Parmar\AppData\Local\Temp\pip-install-_z9eo9si\startup\setup.py", line 7, in <module>
        subprocess.check_call('./gen_manifest.sh')
      File "c:\users\parmar\anaconda3\lib\subprocess.py", line 286, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\users\parmar\anaconda3\lib\subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\users\parmar\anaconda3\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "c:\users\parmar\anaconda3\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    OSError: [WinError 193] %1 is not a valid Win32 application

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Parmar\AppData\Local\Temp\pip-install-_z9eo9si\startup\

Windows 10 64bit home
Python 3.6

**Comment by clchiou** [comment]
Thanks for reporting this issue. I fixed it and released [0.4.0](https://pypi.org/project/startup/0.4.0/).
